### ISSUE TITLE
Get tilt and orientation angles from VCOM

### ISSUE THREAD

**Issue by jamesmhbarry** [meteocontrol/vcom-api-client#7]
Is it possible to get the tilt and orientation angles of a system from the VCOM API?

**Comment by jamesmhbarry** [comment]
> yes, but that system must have tracker device
> 
> see more info from online doc https://meteocontrol.github.io/vcom-api/?shell#trackers

Thanks. I see. It would be quite useful to be able to get the angles for a fixed system too.

**Comment by DerayGa** [comment]
sorry, those info is not available from system detail.

**Comment by DerayGa** [comment]
it’s not vcom-api didn’t provide this info, but this info is not existing in vcom. 
currently vcom only provided latitude, longitude and elevation.

https://meteocontrol.github.io/vcom-api/?shell#system

can’t promise this info will be added in the future

**Comment by moerks** [comment]
@jamesmhbarry @DerayGa I agree that the information enclosed in the technical data endpoint is fairly limited. For sure the parameters you ask for would be helpful and of course the VCOM itself does have information on tilt and orientation for the different sections of a site.  So far this has not been exposed via the API and it's not on the road for the next months. However, I am positive about an addition in the future.

**Comment by jamesmhbarry** [comment]
> @jamesmhbarry @DerayGa I agree that the information enclosed in the technical data endpoint is fairly limited. For sure the parameters you ask for would be helpful and of course the VCOM itself does have information on tilt and orientation for the different sections of a site. So far this has not been exposed via the API and it's not on the road for the next months. However, I am positive about an addition in the future.

Thanks, that would be great indeed. The information would be critical in order to validate irradiance models and one could do a lot with the PV data then... ;)

**Comment by DerayGa** [comment]
sorry, I was wrong and @moerks was right, we do have those info in VCOM  

<img width="373" alt="Screenshot 2023-10-19 at 11 13 15 AM" src="https://github.com/meteocontrol/vcom-api-client/assets/13195089/1ada47e2-c249-4dcd-8833-1c9d601be796">

**Comment by jamesmhbarry** [comment]
Is there any plan to implement this in the near future, i.e that one can access more metadata like tilt and azimuth angles?

**Comment by DerayGa** [comment]
short answer: no 🙅

**Comment by DerayGa** [comment]
sorry for the short answer.  

the issue is that value tilt/azimuth is belong to subsystems
and the result get from technical-data is summary value.  

we can summary nominalPower and siteArea or the number of soalr panels.  
but we can't summary tilt/azimuth angle if there are multiple subsystems.
