### ISSUE TITLE
vcom-api-client setup

### ISSUE THREAD

**Issue by ck-coke** [meteocontrol/vcom-api-client#8]
Hi,

after executing 

`./vendor/bin/phpcs --extensions=php --ignore=vendor,phpcs --report-full -p --standard=phpcs/meteocontrol/ruleset.xml .` 

I get the following error:

`ERROR: the "phpcs/meteocontrol/ruleset.xml" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz and Zend`

How can I solve that?
Everything else went through without any error.

**Comment by philuxx** [comment]
Hi @ck-coke,

the path to the phpcs coding standard needs to be updated.

You can execute the phpcs tests with
```
./vendor/bin/phpcs --extensions=php --ignore=vendor,phpcs --report-full -p --standard=phpcs.xml.dist
```
explicitly passing the path to the standard, or just
```
./vendor/bin/phpcs --extensions=php --ignore=vendor,phpcs --report-full -p
```
as it will be detected by phpcs through its name.

**Comment by albert361** [comment]
Hi @philuxx 
It's so great you help here out :)  

@ck-coke 
The wrong command in README has been fixed.
Thank you!

**Comment by albert361** [comment]
Hi @philuxx
It's so great you help here out :)

@ck-coke
The wrong command in README has been fixed.
Thank you!

**Comment by philuxx** [comment]
Hi @albert361
happy to help :)
