### ISSUE TITLE
Timestamps for Status Events

### ISSUE THREAD

**Issue by jamesmhbarry** [meteocontrol/vcom-api-client#9]
When pulling data from "statuses" via the API, is it possible to get them with exact time stamps, i.e. not in the "interval" resolution but the exact time stamp, i.e. to the second? Sometimes it is important to get the exact time of an event, for instance.

**Comment by DerayGa** [comment]
sorry, it’s not possible because when data import, its timestamp already rectified to its interval. so the “extract original timestamp” is not available anymore.

**Comment by jamesmhbarry** [comment]
OK, so the only way to get these data is through the portal by say importing this directly from a plot in the VCOM portal?
